name: 'dg-corne'
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["sofle_left","sofle_right"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
